---
title: "Matt Pagett"
format:
  html:
    theme: cyborg  
    code-background: true
    highlight-style: github-dark
---

Welcome to my personal website.

## Research interests

- AI and robotics explainability, trustworthiness, and accountability
- Digital humanities
- World models

## Select projects

### Research projects

[EMPO](https://github.com/mensch72/empo) - Empowerment-based AI agents (led by Jobst Heitzig; I am contributing in connection with [AI Safety Initiative Groningen](https://www.aisig.org/research-hub))

### Hackathons

[Cross-Border Agentic AI Compliance (CBAAC): Embedding Regulatory and Cultural Risk Compliance into Agentic Communication
](https://apartresearch.com/project/crossborder-agentic-ai-compliance-cbaac-embedding-regulatory-and-cultural-risk-compliance-into-agentic-communication-p4oo) (with Tomoko Mitsuoka, submitted to Apart Research Technical Governance Hackathon - February 2026)

[Adversarial LLM span detection for social sycophancy observation](https://github.com/mattpagett/sycoverse) (with Pranati Modumudi, submitted to Apart Research AI Manipulation Hackathon - Jan 2026)

[Comparative LLM methods for social media bot detection](https://apartresearch.com/project/comparative-llm-methods-for-social-media-bot-detection-u9s4) (With Andreas Raaskov. 2nd place winner, November 2025 Apart Defensive Acceleration Hackathon)

[Protocop](https://bsky.app/profile/protocop.bsky.social) - social media moderation toolkit using MCP (Entered into MCP 1st Anniversary Hackathon, November 2025)


### Digital humanities

[Cervantes Reader](https://cervantes.mattpagett.dev) (v1) - AI-powered narration/analysis for early modern literature

[Artificial Quartet](https://github.com/mattpagett/artificial-quartet).  An early attempt to use generative AI to write a play.  Submitted as an entry to the Financial Times 2020 Weekend Festival theater contest.


## Resources

### AI Safety

[ENAIS](https://www.enais.co/collab) - The European Network for AI Safety offers worldwide AI safety education. I'm a faciliator for the Winter 2026 AI Safety Collab.

[BlueDot](https://bluedot.org/) provides education about AI safety and governance.  I completed the AGI Strategy and Technical AI Safety courses in 2025 and recommend them to anyone interested in AI risk.

[ARENA](https://www.arena.education/) - detailed technical AI safety course.  I've formed a self-study group on the ARENA Slack channel. 

### Software Development

[SolveIt](https://newsi.fast.ai/?via_id=oi9lxe79) is a course, a method, and a platform to use LLMs thoughtfully in software development (and other areas, like writing).  (*This is an affiliate link - I'll earn a commission and you'll get a discount if you sign up using this link*).  It is led by Jeremy Howard whose [Fast.AI course on Deep Learning](https://course.fast.ai/) remains as relevant and useful as when I first took it in 2019.

## Find me at

[LinkedIn](https://www.linkedin.com/in/matthew-pagett/)

[Github](https://github.com/mattpagett)
